# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Wizard Starter")
        MainWindow.resize(358, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Info = QtWidgets.QListWidget(self.centralwidget)
        self.Info.setObjectName("Info")
        self.verticalLayout.addWidget(self.Info)
        self.ClientPort = QtWidgets.QLineEdit(self.centralwidget)
        self.ClientPort.setObjectName("ClientPort")
        self.verticalLayout.addWidget(self.ClientPort)
        self.ProxyPort = QtWidgets.QLineEdit(self.centralwidget)
        self.ProxyPort.setObjectName("ProxyPort")
        self.verticalLayout.addWidget(self.ProxyPort)
        self.ServerPort = QtWidgets.QLineEdit(self.centralwidget)
        self.ServerPort.setObjectName("ServerPort")
        self.verticalLayout.addWidget(self.ServerPort)
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.Start.setFont(font)
        self.Start.setStyleSheet(" background-color: rgb(0, 255, 0)")
        self.Start.setObjectName("Start")
        self.verticalLayout.addWidget(self.Start)
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.Stop.setFont(font)
        self.Stop.setStyleSheet(" background-color: rgb(255, 0, 0)")
        self.Stop.setObjectName("Stop")
        self.verticalLayout.addWidget(self.Stop)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Wizard Starter", "Wizard Starter"))
        self.Start.setText(_translate("Wizard Starter", "Start"))
        self.Stop.setText(_translate("Wizard Starter", "Stop"))
